name: main Push
on:
  push:
    branches: main
permissions:
  contents: read
  id-token: write
  pages: write
concurrency:
  cancel-in-progress: false
  group: "pages"
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup
        uses: actions/setup-node@v4
        with:
          cache-dependency-path: packages/www
          cache: yarn
          node-version: 20.11.1
      - name: Cache
        uses: actions/cache@v4
        with:
          path: packages/www/.next/cache
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/yarn.lock') }}-${{ hashFiles('**.[jt]s', '**.[jt]sx') }}
          restore-keys: ${{ runner.os }}-nextjs-${{ hashFiles('**/yarn.lock') }}-
      - name: Dependencies
        run: yarn install
        working-directory: packages/www
      - name: Format
        run: yarn format:check
        working-directory: packages/www
      - name: Lint
        run: yarn lint:check
        working-directory: packages/www
      - name: Build
        run: yarn build
        working-directory: packages/www
      - name: Upload
        uses: actions/upload-pages-artifact@v3
        with:
          path: packages/www/out
  deploy:
    name: Deploy
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v4
